import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tinylink Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
        >
          <header className="border-b border-zinc-800 bg-gradient-to-r from-zinc-950 via-black to-zinc-900">
            <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
              <div className="text-lg font-semibold text-white">Tinylink</div>
              <nav className="flex items-center gap-3">
                <SignedOut>
                  <div className="flex items-center gap-3">
                    <SignInButton mode="modal" fallbackRedirectUrl="/dashboard" asChild>
                      <Button asChild variant="outline" size="lg" className="border-zinc-700 text-white">
                        <span>Sign in</span>
                      </Button>
                    </SignInButton>
                    <SignUpButton mode="modal" afterSignUpUrl="/dashboard" asChild>
                      <Button asChild size="lg">
                        <span>Create account</span>
                      </Button>
                    </SignUpButton>
                  </div>
                </SignedOut>
                <SignedIn>
                  <UserButton
                    appearance={{
                      elements: { avatarBox: "h-9 w-9" },
                    }}
                  />
                </SignedIn>
              </nav>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
